AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation Template to Create a DynamoDB Table (On-Demand) for Account Details

Resources:
  AccountDetailsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CWM-Account-Details-Table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: AccountId
          AttributeType: S
        - AttributeName: CustomerEmailIds
          AttributeType: S
      KeySchema:
        - AttributeName: AccountId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CustomerEmailIdsIndex
          KeySchema:
            - AttributeName: CustomerEmailIds
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Name
          Value: CWM-Account-Details-Table
        - Key: Environment
          Value: Development

Outputs:
  TableName:
    Description: "DynamoDB Table Name"
    Value: !Ref AccountDetailsTable
